export enum ErrorCodes {
    ERR_VALIDATION = 'ERR_VALIDATION',
    ERR_AUTHENTICATION = 'ERR_AUTHENTICATION',
    ERR_NOT_FOUND = 'ERR_NOT_FOUND',
    ERR_INTERNAL_SERVER_ERROR = 'ERR_INTERNAL_SERVER_ERROR',
    ERR_FORBIDDEN = 'ERR_FORBIDDEN',
    ERR_BAD_REQUEST = 'ERR_BAD_REQUEST',
    ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
}