export enum SuccessCodes {
    SUCCESS_CREATED = 'SUCCESS_CREATED',
    SUCCESS_UPDATED = 'SUCCESS_UPDATED',
    SUCCESS_DELETED = 'SUCCESS_DELETED',
    SUCCESS_FETCHED = 'SUCCESS_FETCHED',
    SUCCESS_AUTHENTICATED = 'SUCCESS_AUTHENTICATED',
}